package com.mandi.notification;

public enum NotificationType {
    COMPLAINT_CREATED,
    COMPLAINT_ASSIGNED,
    TASK_ACCEPTED,
    WORK_STARTED,
    PROGRESS_UPDATED,
    WORK_COMPLETED,
    VERIFICATION_REQUESTED,
    COMPLAINT_REOPENED,
    FEEDBACK_SUBMITTED,
    COMPLAINT_CLOSED,
    SLA_OVERDUE,
    ESCALATION,
    ANNOUNCEMENT,
    BOOKING_REQUEST,
    BOOKING_ACCEPTED,
    BOOKING_REJECTED,
    BOOKING_RESCHEDULED,
    BOOKING_COMPLETED,
    CROP_ORDER,
    TRANSPORT_REQUEST,
    COORDINATION_REQUEST,
    CHAT
}
