package com.mandi.user;

public enum Role {
    ROLE_CITIZEN,
    ROLE_FARMER,
    ROLE_WORKER,
    ROLE_VOLUNTEER,
    ROLE_DONOR,
    ROLE_NGO,
    ROLE_SERVICE_PROVIDER,
    ROLE_TRANSPORT_PROVIDER,
    ROLE_MANDI_MITRA,
    ROLE_BLOCK_COORDINATOR,
    ROLE_DISTRICT_COORDINATOR,
    ROLE_ORGANIZATION,
    ROLE_GOVERNMENT_OFFICIAL,
    ROLE_ADMIN,
    ROLE_SUPER_ADMIN,
    ROLE_MODERATOR
}
